### PR TITLE
[feat] add MulAddAssign trait

### PR DESCRIPTION
**Pull request by lightsing**
patch to fit ff crate with MulAddAssign trait

### CODE REVIEW

**Comment by lightsing** [comment]
cc @lispc @kunxian-xia

**Comment by lispc** [comment]
why this pr is based on main while https://github.com/scroll-tech/halo2curves/pull/7 is based on base-0.3.0? @lightsing

**Comment by lispc** [comment]
is this `feat/mul-add-assign` used anywhere?  since seems we never use the `main` branch ?

**Comment by lispc** [comment]
no longer useful

**Pull request closed without merging**
